### PR TITLE
support passing HTTP headers via ENV

### PR DESCRIPTION
**Pull request by csmuc**
This PR adds support to for passing HTTP headers. Both internal Rack requests and USE_SERVER is supported.

I added this while benchmarking API endpoints, which require some specific HTTP headers.

### CODE REVIEW

**Comment by amedrz** [comment]
This is just what I needed, works great! Thanks @csmuc 

@schneems would you be able to merge this anytime soon?

**Comment by schneems** [comment]
Boom, done. Can you try on master and let me know if it works out?

Thanks for the PR!

**Comment by amedrz** [comment]
It does! Thanks

**Comment by yjukaku** [comment]
Hey @schneems , thanks for your work on this library. Do you think you could push out a new release for this gem? I would love to be able to use those HTTP headers 😇

**Pull request merged**
