### PR TITLE
Compatibility with rake 12

### PR DESCRIPTION
**Pull request by mrdomino**

### CODE REVIEW

**Comment by schneems** [comment]
So tests are botched :(

Do the tests work for you locally?

**Comment by mrdomino** [comment]
D'oh, I didn't run them. I'll take a look when I get a chance.

**Comment by giedriusr** [comment]
Any news on upgrade?

**Comment by schneems** [comment]
it's harder than it looks. #90

**Comment by mrdomino** [comment]
Closing in favor of #90, thanks and sorry 'bout that!

**Pull request closed without merging**
