### PR TITLE
Add a task for testing app cold start

### PR DESCRIPTION
**Pull request by viraptor**
The `stackprof_warmup` task does a specific kind of profiling, different
from standard `stackprof`. It does 1 + TEST_COUNT requests, saving a
separate stackprof dump of each of them with a smaller resolution.

The first one is saved as `tmp/....dump.cold`, while the following ones
are `tmp/....dump.warm.N`. This allows other tools to process the output
and extract the difference between the cold and warm request behaviour.

Unfortunately stackprof itself doesn't include the necessary tools, so
no default report is produced from this task.

### CODE REVIEW

**Comment by schneems** [comment]
Cool idea!

As long as you're testing for longer than it takes too boot, I would think that boot doesn't impact tests that much? Have you seen significant impact in stackprof output?

**Comment by viraptor** [comment]
I'm not sure I understand your question about boot, but will try to answer anyway ;) Here's some context:

The output from this test is supposed to work with the analyser I wrote: https://github.com/viraptor/rails_cold_spots

In practice, with a big enough app, there are 3 interesting timeframes: (with timings from the app I wrote this for)
- app is booting (>30s)
- first request where framework/app data is not cached yet (>3s)
- following requests (<100ms)

Since only the last 2 phases actually get user traffic, I wanted to ignore the boot phase. This test is only supposed to answer the "what happens in the second phase, but not the third". This allows pointing out things like "you're spending 500ms processing/caching this partial template", or "you're spending 10ms doing initial query to get the model's schema", which can then be explicitly moved to the initializers instead.

It probably matters for huge apps more than small ones (when your 300+ models take in total 4+ seconds to cache the schema, for example), and you don't want your post-deploy initial requests time to be suffered by customers (delay on each different controller * no of workers * no of servers gets significant).

**Comment by viraptor** [comment]
Aaand I described some of it in README update, which I forgot to commit. I'll add it later, sorry.

**Comment by viraptor** [comment]
Well, that took a bit longer... But let's get this implemented.

**Comment by schneems** [comment]
Thanks for the PR, sorry it took me so long to respond. I think you can run all of the benchmarks with `TEST_COUNT=1` to get cold start info. If there's some other settings that prevent that, then maybe let's try to make this generalizable.

**Comment by viraptor** [comment]
So the magic here is in making more than one request to get *only* the cold part. Specifically, let's say the app does something like this:

```
def foodata
  @foodata = generate_foodata
end
def foodata
  process(foodata)
end
```
or some other case of caching.

What I'm interested here is the `generate_foodata` only. By running with this PR, I'll get that function in the cold trace but not any of the warm ones. That means I can post-process to get `(cold - (warm1 + warm2 + ...))` which will contain `generate_foodata` but not `process`.

**Pull request closed without merging**
