### PR TITLE
Avoid loading source annotation extractor

### PR DESCRIPTION
**Pull request by benoittgt**
Fix: https://github.com/schneems/derailed_benchmarks/issues/128

The way we are loading the library is probably not the way it was meant. This is a quick-fix, it can probably be done in a better way.

What happens is:
1. We try to load [source_annotation_extractor.rb](https://github.com/rails/rails/blob/6-0-stable/railties/lib/rails/source_annotation_extractor.rb#L7-L8) but it is deprecated
2. The deprecation created with 
    ```ruby
    SourceAnnotationExtractor = ActiveSupport::Deprecation::DeprecatedConstantProxy.
    new("SourceAnnotationExtractor", "Rails::SourceAnnotationExtractor")
    ```
    ends with an empty deprecator. This is a weird behavior. Because we are not providing `deprecator` param by default it is `ActiveSupport::Deprecation.instance`
3. With a `puts` inside [`initialize`](https://github.com/rails/rails/blob/14931e537f3dcd522b68a5b640aa47272602a137/activesupport/lib/active_support/deprecation/proxy_wrappers.rb#L124) and a `puts` inside [`def warn`](https://github.com/rails/rails/blob/14931e537f3dcd522b68a5b640aa47272602a137/activesupport/lib/active_support/deprecation/proxy_wrappers.rb#L148) the first `deprecator` is properly instantiated, but it is `nil` in `def warn`.
    ```
    in initialize
    @deprecator = #<ActiveSupport::Deprecation:0x00007ff2bfbcbe48 @gem_name="Rails", 
    @deprecation_horizon="6.1", @silenced=false, @debug=false>
    ############################################################
    in warn
    @depreactor = nil
    ```
    I tried to freeze the object `deprecator` at the end of initialize with `@deprecator.freeze` as mentioned in [Tenderlove guide](https://tenderlovemaking.com/2016/02/05/i-am-a-puts-debuggerer.html#an-object-is-being-mutated-but-i-dont-know-where) (<3) but it didn't raise any error.
    Why we have an empty `@deprecator`? It is because we have on the top [`instance_methods.each { |m| p m; undef_method m unless /^__|^object_id$/.match?(m) }`](https://github.com/rails/rails/blob/14931e537f3dcd522b68a5b640aa47272602a137/activesupport/lib/active_support/deprecation/proxy_wrappers.rb#L13), introduced [long time ago](https://github.com/rails/rails/commit/0e73a92c0441fb7faec3ac44dbaa8fbf8335df10#diff-56d82b31f5aa0652e85b086f71b77623R77). If we do that change
```diff
--- a/activesupport/lib/active_support/deprecation/proxy_wrappers.rb
+++ b/activesupport/lib/active_support/deprecation/proxy_wrappers.rb
@@ -10,7 +10,7 @@ def self.new(*args, &block)
         super
       end

-      instance_methods.each { |m| undef_method m unless /^__|^object_id$/.match?(m) }
+      instance_methods.each { |m| undef_method m unless /^__|require|^object_id$/.match?(m) }
```
It works. But first I need to understand why we need to undef all methods.

In the meantime this patch should work.
    

Maybe @sikachu (👋) have a better idea on this because he worked on https://github.com/rails/rails/pull/32065?

To reproduce: https://github.com/benoittgt/testing_6_0_0_rc1/tree/derailed

### CODE REVIEW

**Comment by benoittgt** [comment]
Probably some fun to fix the CI 😁

**Comment by schneems** [comment]
Thanks for your work here. Strangely enough CI hits this error on other runs such as https://github.com/schneems/derailed_benchmarks/pull/132 but I can't trigger it on my machine. 

I'm not entirely sure what exactly is causing the bug, but it does look like a bug in Rails. I would love to be able to reproduce this outside of derailed and get it fixed inside of Rails. 

Do you have any time you might be willing to pair on me with this? If not, I can put a short term shim like this into the code, but in my experience short term fixes tend to live well beyond their original expiration dates.

**Comment by benoittgt** [comment]
Hey Richard

After opening this PR I tried to dig into `ActiveSupport::Deprecation` to understand why we have this kind of behavior but didn't find a clear answer.

I will be happy to pair with you on this one and don't use this temporary quick fix.

**Comment by benoittgt** [comment]
For the moment I am not able to reproduce the issue locally but I probably miss something with derailed.

This is my ruby script:

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", path: '~/code/rails', require: false
end

FILES = [
  "rails/engine/configuration",
  "rails/source_annotation_extractor",
  "active_support/deprecation"
]

puts "#" * 60
puts "With Kernel.require"
FILES.each do |file|
  p Kernel.require(file)
end
puts

###########
module Kernel
  alias :original_require :require
  REQUIRE_STACK = []

  def require(file)
    Kernel.require(file)
  end

  # This breaks things, not sure how to fix
  # def require_relative(file)
  #   Kernel.require_relative(file)
  # end
  class << self
    alias :original_require          :require
    # alias :original_require_relative :require_relative
  end
end

puts "#" * 60
puts "With original_require"
FILES.each do |file|
  p original_require(file)
end
puts

puts "#" * 60
puts "With original_require and define_singleton_method"
FILES.each do |file|
  Kernel.define_singleton_method(:require) do |file|
    p original_require(file)
  end
end
```

Output
```
Fetching gem metadata from https://rubygems.org/.............
Fetching gem metadata from https://rubygems.org/............
Fetching gem metadata from https://rubygems.org/............
Resolving dependencies...
Using rake 12.3.2
Using concurrent-ruby 1.1.5
Using thread_safe 0.3.6
Using crass 1.0.4
Using rack 2.0.7
Using minitest 5.11.3
Using mini_portile2 2.4.0
Using builder 3.2.3
Using bundler 2.0.1
Using nio4r 2.3.1
Using websocket-extensions 0.1.4
Using mimemagic 0.3.3
Using mini_mime 1.0.1
Using erubi 1.8.0
Using method_source 0.9.2
Using thor 0.20.3
Using i18n 1.6.0
Using tzinfo 1.2.5
Using rack-test 1.1.0
Using sprockets 3.7.2
Using nokogiri 1.10.3
Using websocket-driver 0.7.1
Using marcel 0.3.3
Using mail 2.7.1
Using activesupport 6.0.0.alpha from source at `~/code/rails`
Using loofah 2.2.3
Using rails-html-sanitizer 1.0.4
Using rails-dom-testing 2.0.3
Using globalid 0.4.2
Using actionview 6.0.0.alpha from source at `~/code/rails`
Using activemodel 6.0.0.alpha from source at `~/code/rails`
Using activejob 6.0.0.alpha from source at `~/code/rails`
Using actionpack 6.0.0.alpha from source at `~/code/rails`
Using activerecord 6.0.0.alpha from source at `~/code/rails`
Using actioncable 6.0.0.alpha from source at `~/code/rails`
Using actionmailer 6.0.0.alpha from source at `~/code/rails`
Using railties 6.0.0.alpha from source at `~/code/rails`
Using sprockets-rails 3.2.1
Using activestorage 6.0.0.alpha from source at `~/code/rails`
Using actionmailbox 6.0.0.alpha from source at `~/code/rails`
Using actiontext 6.0.0.alpha from source at `~/code/rails`
Using rails 6.0.0.alpha from source at `~/code/rails`
############################################################
With Kernel.require
true
____________________________________________________________
Hello from railties/lib/rails/source_annotation_extractor.rb:10
____________________________________________________________
true
false

############################################################
With original_require
false
false
false

############################################################
With original_require and define_singleton_method

**Comment by benoittgt** [comment]
Switch a simpler and much cleaner patch 
https://github.com/schneems/derailed_benchmarks/pull/134

**Pull request closed without merging**
