### PR TITLE
first commit

### PR DESCRIPTION
**Pull request by syiin**
not sure of the intent behind the ensure block but there was no preceding begin and the identation gave no clue so this was just my small fix

### CODE REVIEW

**Comment by schneems** [comment]
The ensure is required. But I forgot that’s not a syntax that works on older versions of Ruby. We need to explicitly wrap everything with begin/end for the ensure block to work correctly. Can you update the PR to wrap the whole task with begin/end.

**Comment by syiin** [comment]
> The ensure is required. But I forgot that’s not a syntax that works on older versions of Ruby. We need to explicitly wrap everything with begin/end for the ensure block to work correctly. Can you update the PR to wrap the whole task with begin/end.

got it

**Comment by syiin** [comment]
`Expected to find a manifest file in `app/assets/config/manifest.js` (Sprockets::Railtie::ManifestNeededError)

But did not, please create this file and use it to link any assets that need`

This seems to be the error causing the tests to fail?

**Comment by schneems** [comment]
Thanks for the PR! Can you send me another one to add Ruby 2.4.4 to the test matrix in .travis.yml?

**Pull request merged**
